---
- name: Verify and Monitor RHEL services
  hosts: all
  vars:
    email_address: "your_email@example.com"  # Replace with your alert email
  tasks:

    - name: Verify and install services
      when: action == "verify_install"
      block:
        - name: Verify httpd installation on host1
          when: inventory_hostname == "host1"
          yum:
            name: httpd
            state: present

        - name: Verify rabbitmq-server installation on host2
          when: inventory_hostname == "host2"
          yum:
            name: rabbitmq-server
            state: present

        - name: Verify postgresql installation on host3
          when: inventory_hostname == "host3"
          yum:
            name: postgresql-server
            state: present

    - name: Check disk usage and send alert if usage > 80%
      when: action == "check-disk"
      block:
        - name: Check disk usage
          shell: "df -h | awk '$5 > 80 {print $0}'"
          register: disk_usage
          ignore_errors: yes

        - name: Send alert email if high disk usage found
          mail:
            host: localhost
            port: 25
            to: "{{ email_address }}"
            subject: "Disk Usage Alert on {{ inventory_hostname }}"
            body: "{{ disk_usage.stdout }}"
          when: disk_usage.stdout != ""

    - name: Check application status
      when: action == "check-status"
      block:
        - name: Get the application status via REST API
          uri:
            url: "http://{{ hostvars['host1'].ansible_host }}:5000/healthcheck"
            method: GET
            return_content: yes
          register: healthcheck

        - name: Display application status
          debug:
            msg: "Application Status: {{ healthcheck.json.application_status }}"

        - name: Check individual service status
          block:
            - name: Check httpd status
              uri:
                url: "http://{{ hostvars['host1'].ansible_host }}:5000/healthcheck/httpd"
                method: GET
                return_content: yes
              register: httpd_status

            - name: Check rabbitmq status
              uri:
                url: "http://{{ hostvars['host1'].ansible_host }}:5000/healthcheck/rabbitmq-server"
                method: GET
                return_content: yes
              register: rabbitmq_status

            - name: Check postgresql status
              uri:
                url: "http://{{ hostvars['host1'].ansible_host }}:5000/healthcheck/postgresql"
                method: GET
                return_content: yes
              register: postgresql_status

          always:
            - name: Display services down
              debug:
                msg: >
                  Services Down: {{
                    (httpd_status.json.service_status != 'UP' | ternary('httpd', ''))
                    + (rabbitmq_status.json.service_status != 'UP' | ternary(' rabbitmq-server', ''))
                    + (postgresql_status.json.service_status != 'UP' | ternary(' postgresql', ''))
                  | trim }}
